In [1]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import cross_validation,preprocessing
from sklearn.linear_model import LinearRegression



/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [3]:
df = pd.read_csv("/home/shivam/BE_Project/BE_Project/static/CAW.csv")
df

Year     Rape  Kidnapping and Abduction of Women & Girls  Dowry Deaths  \
0   2001  16075.0                                    14645.0        6851.0   
1   2002  16373.0                                    14506.0        6822.0   
2   2003  15847.0                                    13296.0        6208.0   
3   2004  18233.0                                    15578.0        7026.0   
4   2005  18359.0                                    15750.0        6787.0   
5   2006  19348.0                                    17414.0        7618.0   
6   2007  20737.0                                    20416.0        8093.0   
7   2008  21467.0                                    22939.0        8172.0   
8   2009  21397.0                                    25741.0        8383.0   
9   2010  22172.0                                    29795.0        8391.0   
10  2011  24206.0                                    35565.0        8618.0   
11  2012  24923.0                                    38262.0        8233.0   
12  2013  33707.0                                    51881.0        8083.0   
13  2014  36735.0                                    57311.0        8455.0   
14  2015  34651.0                                    59277.0        7634.0   
15  2016  38947.0                                    64519.0        7621.0   
16  2017      NaN                                        NaN           NaN   

    Assault on women with intent to outrage her modesty  \
0                                             34124.0     
1                                             33943.0     
2                                             32939.0     
3                                             34567.0     
4                                             34175.0     
5                                             36617.0     
6                                             38734.0     
7                                             40413.0     
8                                             38711.0     
9                                             40613.0     
10                                            42968.0     
11                                            45351.0     
12                                            70739.0     
13                                            82235.0     
14                                            82422.0     
15                                            84746.0     
16                                                NaN     

    Insult to the modesty of Women  Cruelty by Husband or his relatives  \
0                           9746.0                              49170.0   
1                          10155.0                              49237.0   
2                          12325.0                              50703.0   
3                          10001.0                              58121.0   
4                           9984.0                              58319.0   
5                           9966.0                              63128.0   
6                          10950.0                              75930.0   
7                          12214.0                              81344.0   
8                          11009.0                              89546.0   
9                           9961.0                              94041.0   
10                          8570.0                              99135.0   
11                          9173.0                             106527.0   
12                         12589.0                             118866.0   
13                          9735.0                             122877.0   
14                          8685.0                             113403.0   
15                          7305.0                             110378.0   
16                             NaN                                  NaN   

    Importation of Girls from Foreign Country  Immoral Traffic (P) Act  \
0                                         114                   8796.0   
1                                    

In [258]:
X = df.iloc[:,:-1].values
y = df.iloc[:,12].values
X_train,X_test,y_train,y_test = cross_validation.train_test_split(X,y,test_size=0.2)

regressor = LinearRegression()
regressor.fit(X_train,y_train)

print "Your Test Set is:- \n",X_test
#X_tst = np.array([2015, 0, 0,  0, 0, 0, 0, 0, 0, 0,  0, 0])
accuracy = regressor.score(X_test,y_test)
print "\nYour Prediction has the accuracy of-",accuracy*100,"%"

y_prediction = regressor.predict(X_test)
print "\nPredicted Total Crime for above given years is:-\n",y_prediction

Your Test Set is:- 
[[ 2009 21397 25741  8383 38711 11009 89546    48  2474  5650   845     0]
 [ 2005 18359 15750  6787 34175  9984 58319   149  5908  3204  2917     1]
 [ 2010 22172 29795  8391 40613  9961 94041    36  2499  5182   895     0]]

Your Prediction has the accuracy of- 99.999999987 %

Predicted Total Crime for above given years is:-
[ 203804.06126778  155553.3971474   213584.69932794]


In [259]:
rapeX = df.iloc[:,0].values
rapeY = df.iloc[:,1].values

#rapeX_train,rapeX_test,rapeY_train,rapeY_test = cross_validation.train_test_split(rapeX,rapeY,test_size=0.1)
rapeX_test = np.array([2015,2016,2017,2018,2019,2020])

print "Your Test Set is:- \n",rapeX_test

clf=LinearRegression()    #clf is the regression classifier
clf.fit(rapeX.reshape(-1, 1),rapeY)   #reshape to convert it from 1 dimentional array to 2D array.
#accuracy = clf.score(rapeX_test.reshape(-1, 1),rapeY_test)
#print accuracy
rapePredict = clf.predict(rapeX_test.reshape(-1,1))
print "\nPredicted Total Crime for above given years is:-\n",rapePredict

Your Test Set is:- 
[2015 2016 2017 2018 2019 2020]

Predicted Total Crime for above given years is:-
[ 32146.15384615  33483.93626374  34821.71868132  36159.5010989
  37497.28351648  38835.06593407]


In [239]:
'''plt.scatter(rapeX,rapeY,color = 'red')
plt.plot(rapeX, clf.predict(rapeX.reshape(1,-1)), color = 'blue')
plt.title("Rape Crime against Women")
plt.xlabel("Year")
plt.ylabel("Rape Cases Reported")
plt.show()

'''

'plt.scatter(rapeX,rapeY,color = \'red\')\nplt.plot(rapeX, clf.predict(rapeX.reshape(1,-1)), color = \'blue\')\nplt.title("Rape Crime against Women")\nplt.xlabel("Year")\nplt.ylabel("Rape Cases Reported")\nplt.show()\n\n'